### PR TITLE
Minor fixups

### PR DESCRIPTION
**Pull request by 2uasimojo**
A grab-bag of small nonfunctional changes.
- Add some more formatting to the output of openshift/golang-osd-operator's `update` script.
- Consistent error formatting in prow-config (fup from https://github.com/openshift/boilerplate/pull/75#discussion_r507851220)
- Rename a handful of test case files from snake_case to kebab-case for consistency.
- Get rid of trailing whitespace, which shows up in annoying ugly red in diffs when consumers onboard.

### CODE REVIEW

**Comment by arjunrn** [comment]
I would recommend that we use [shellcheck](https://github.com/koalaman/shellcheck) as a check for PRs. And also verify that no files have trailing spaces. Not in this PR of course but as a followup.

**Comment by 2uasimojo** [comment]
> I would recommend that we use [shellcheck](https://github.com/koalaman/shellcheck) as a check for PRs. And also verify that no files have trailing spaces. Not in this PR of course but as a followup.

Cool! I'll look into that.

Otherwise, we okay with this PR?

**Comment by 2uasimojo** [comment]
> I would recommend that we use [shellcheck](https://github.com/koalaman/shellcheck) as a check for PRs. And also verify that no files have trailing spaces. Not in this PR of course but as a followup.

I opened https://issues.redhat.com/browse/OSD-5580 so we don't lose sight of this.

**Pull request merged**
