### PR TITLE
Subscribe compliance-audit-router (CAR) to boilerplate

### PR DESCRIPTION
**Pull request by clcollins**
Adds openshift/compliance-audit-router (CAR) to the boilerplate subscribers.yaml, with the osd-container-image convention.

Signed-off-by: Chris Collins <collins.christopher@gmail.com>

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Looks correct to me, gels with https://github.com/openshift/compliance-audit-router/blob/main/boilerplate/update.cfg

Note that this file is really only used by [subscriber tools](https://github.com/openshift/boilerplate/blob/master/doc/subscriber.md). Those are handy, but if you're not going to use them, there's nothing forcing you to register.

**Comment by 2uasimojo** [comment]
/retest

ill infra

**Review by mjlshen — APPROVED** [review]
/lgtm

**Pull request merged**
