### PR TITLE
Switch to GitHub

### PR DESCRIPTION
**Pull request by bdematte**
Updating references to the former gitlab repo to the new github one

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Thanks @bdematte. Would you please peel this off of #1?

As a followup, it would be nice to put this var and its defaulting logic into [common.sh](https://github.com/openshift/boilerplate/blob/de5bdf73086d8c77dab94fe0d500de263e905991/boilerplate/_lib/common.sh). (IIRC it was going to be tricky to source that into the main update driver, but I may be misremembering that.)

/hold for rebase

**Comment by bdematte** [comment]
rebased on master. Good for you @2uasimojo ?

**Comment by 2uasimojo** [comment]
Yup, thanks @bdematte 

/lgtm

**Comment by 2uasimojo** [comment]
I'm going to close and reopen this to see if that'll kick prow, which just got set up.

**Pull request merged**
