### PR TITLE
Update catalog-build.sh

### PR DESCRIPTION
**Pull request by georgettica**
Based on https://github.com/georgettica/route-monitor-operator/pull/4
Which is automated

### CODE REVIEW

**Comment by 2uasimojo** [comment]
This seems like a reasonable thing to do, but I'd like to see some evidence that it works first. ISTR we had compat problems with 4.9, which is why we didn't move to it right away.

**Comment by georgettica** [comment]
how do we run the testing?
is there a dry run I can invoke?

**Comment by 2uasimojo** [comment]
> how do we run the testing? is there a dry run I can invoke?

You can pull this change into a fully onboarded OSD operator (so not RMO) and run it through [this process](https://github.com/openshift/boilerplate/blob/master/boilerplate/openshift/golang-osd-operator/app-sre.md). That will build (operator and) catalog images and push them to your personal quay repo. From there you can install them in a scratch cluster. (Obviously to test this particular change you will need to install from the catalog via OLM -- just swapping out the operator image is not sufficient.)

**Comment by ravitri** [comment]
@georgettica - A recent change involving PR https://github.com/openshift/boilerplate/pull/218 updated this image to 4.10 as well along with rebuilding the registry image using ubi-micro base image. Thus, we could close this PR in favor of it.

**Pull request closed without merging**
