### PR TITLE
image-v0.5.0: more go helpers (OSD-6493)

### PR DESCRIPTION
**Pull request by 2uasimojo**
Add the following to the backing image:
- controller-gen
- kustomize
- go-bindata
- operator-sdk v1.2.0

[OSD-6493](https://issues.redhat.com/browse/OSD-6493)

### CODE REVIEW

**Review by NautiluX — COMMENTED** [review]
I added operator-sdk v1.2.0
/lgtm
/hold
leaving it to you to merge when ready

**Comment by jharrington22** [comment]
Are these dependencies of operator sdk 1.x @NautiluX @2uasimojo ?

**Comment by 2uasimojo** [comment]
> Are these dependencies of operator sdk 1.x @NautiluX @2uasimojo ?

Yes, see OSD-6493

**Comment by 2uasimojo** [comment]
Suspect this used cached results. The tags are correct now.

/test pr-check

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Comment by jharrington22** [comment]
@2uasimojo is this ready to merge?

**Comment by 2uasimojo** [comment]
> @2uasimojo is this ready to merge?

Yes. Please remove the hold when you've reviewed.

**Pull request merged**
