### PR TITLE
Remove support for hack/generate-operator-bundle.py

### PR DESCRIPTION
**Pull request by 2uasimojo**
Support for using a "local" (within the consuming repo)
hack/generate-operator-bundle.py script was included as a bridge while
consumers were cutting over to use the common bundle generator. That has
happened. Get rid of the old script, make targets, and support.

### CODE REVIEW

**Comment by cblecker** [comment]
Is this still a change that would need to be made @2uasimojo ?

**Comment by 2uasimojo** [comment]
@cblecker it's just cleanup, removing dead code. Not important for function. If someone is willing to review, I'd be happy to rebase -- just didn't want to chase it if nobody's looking :)

**Comment by cblecker** [comment]
If it still applies, yes, I'll be happy to review.

**Comment by 2uasimojo** [comment]
> I'll be happy to review.

Thanks!

Rebased.

/assign @cblecker 

The delta includes removing some branches and thus dedenting, so you may wish to review with whitespace ignored.

**Pull request merged**
