### PR TITLE
Switch to RHEL8 builder image

### PR DESCRIPTION
**Pull request by cblecker**
Switches and updates the base builder image to the OCP sanctioned RHEL8 image

### CODE REVIEW

**Comment by 2uasimojo** [comment]
See [doc](https://github.com/openshift/boilerplate/#build-images) for help with the tagging requirement to fix pr-check.

**Comment by cblecker** [comment]
@2uasimojo Tag pushed per directions, but it's still failing it seems.

**Comment by 2uasimojo** [comment]
Need to update that tag in a couple of other places. See e.g. https://github.com/openshift/boilerplate/pull/180

**Comment by 2uasimojo** [comment]
Just need to move the new tag onto the new commit (88fa32dc58fb8740f9d006aa5a3668ef4f59ef7f) and re-push it to origin & upstream.

**Comment by 2uasimojo** [comment]
clean rebase

/lgtm

**Pull request merged**
