### PR TITLE
Fix incorrect bash syntax in build image

### PR DESCRIPTION
**Pull request by supreeth7**
PR to fix failing App-SRE deploy pipeline due to incorrect bash syntax.

### CODE REVIEW

**Comment by supreeth7** [comment]
/assign @2uasimojo 

I got the tagging right as per the docs but the pr-check is failing.

**Comment by 2uasimojo** [comment]
I suspect we were getting cached results :angry: 
I [asked](https://coreos.slack.com/archives/CBN38N3MW/p1652201612538429) dptp to scrub the build so we can get a fresh run.

/test pr-check

**Comment by 2uasimojo** [comment]
That did the trick.

/lgtm

**Comment by supreeth7** [comment]
Thanks @2uasimojo!
Legend.

**Pull request merged**
