### PR TITLE
openshift/golang-osd-operator: openapi-gen

### PR DESCRIPTION
**Pull request by 2uasimojo**
Make consumers produce openapi by adding a target called `openapi-generate` which runs `openapi-gen` if necessary. Put it in the chain for `generate`.

### CODE REVIEW

**Comment by arjunrn** [comment]
Is it possible to add a test for this target. Or is it overkill?

**Comment by 2uasimojo** [comment]
> Is it possible to add a test for this target. Or is it overkill?

It's already tested as part of 01-generated-files-checker. I added a condition in there to explicitly check the existence of the file generated by the new directive.

**Comment by arjunrn** [comment]
/lgtm
/hold
Holding for other reviewers

**Pull request merged**
